require("options")
require("keymaps")
require("general")

require("config.plugins")

require("config.colorschemes")

require("config.treesitter")
require("config.completion")
require("config.lsp")
require("config.formatting")
require("config.telescope")
require("config.git")
require("config.dap")
require("config.markdown")
-- require("config.noice")
require("config.obsidian")
require("config.snacks")
require("config.hop")
require("config.grugfar")

require("config.misc")
require("config.which-key")
require("config.harpoon")
require("config.surround")
require("config.lualine")
require("config.indent-blankline")
