local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.smartindent = true
opt.smarttab = true
opt.autoindent = true
opt.wrap = true
opt.ignorecase = true
opt.smartcase = true
opt.termguicolors = true
opt.signcolumn = "yes"
opt.updatetime = 250
opt.clipboard = "unnamedplus" -- sync with Windows clipboard
opt.splitright = true
opt.splitbelow = true
opt.linebreak = true
opt.hlsearch = true
opt.incsearch = true
opt.selection = "inclusive"
opt.swapfile = false
opt.encoding = "UTF-8"
opt.fileencoding = "UTF-8"
opt.mouse = "a"
opt.conceallevel = 1
opt.completeopt = "menu,menuone,noselect,fuzzy"
opt.path = ".,**"
opt.undofile = true
opt.winborder = "rounded"
opt.cmdheight = 0
opt.inccommand = "split"
-- opt.breakindent = true
opt.backspace = { "start", "eol", "indent" }
opt.laststatus = 3
opt.showcmd = true
opt.showcmdloc = "statusline"
