local o = vim.opt

o.number = true
o.relativenumber = true
o.tabstop = 2
o.shiftwidth = 2
o.expandtab = true
o.smartindent = true
o.smarttab = true
o.autoindent = true
o.wrap = true
o.ignorecase = true
o.smartcase = true
o.termguicolors = true
o.signcolumn = "yes"
o.updatetime = 250
o.clipboard = "unnamedplus" -- sync with Windows clipboard
o.splitright = true
o.splitbelow = true
o.linebreak = true
o.hlsearch = true
o.incsearch = true
o.selection = "inclusive"
o.swapfile = false
o.encoding = "UTF-8"
o.fileencoding = "UTF-8"
o.mouse = "a"
o.conceallevel = 1
o.completeopt = "menu,menuone,noselect,fuzzy"
o.path = ".,**"
o.undofile = true
o.winborder = "rounded"
-- o.cmdheight = 0 -- hides cmdline behind statusline
o.inccommand = "split"
-- opt.breakindent = true
o.backspace = { "start", "eol", "indent" }
o.laststatus = 3
o.showcmd = true
o.showcmdloc = "statusline"
o.timeoutlen = 200
