local harpoon = require("harpoon")
harpoon:setup()
local map = vim.keymap.set

map("n", "<leader>a", function()
	harpoon:list():add()
end, { desc = "harpoon: add file" })
map("n", "<leader>m", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "harpoon: menu" })
map("n", "<leader>1", function()
	harpoon:list():select(1)
end, { desc = "harpoon: file 1" })
map("n", "<leader>2", function()
	harpoon:list():select(2)
end, { desc = "harpoon: file 2" })
map("n", "<leader>3", function()
	harpoon:list():select(3)
end, { desc = "harpoon: file 3" })
map("n", "<leader>4", function()
	harpoon:list():select(4)
end, { desc = "harpoon: file 4" })
map("n", "<leader>]", function()
	harpoon:list():next()
end, { desc = "harpoon: next" })
map("n", "<leader>[", function()
	harpoon:list():prev()
end, { desc = "harpoon: prev" })
