---------------------------------------------------------------------
-- Jump to label (Helix `gw` style)
---------------------------------------------------------------------
require("hop").setup({ keys = "etovxqpdygfblzhckisuran" })
local hop = require("hop")
-- Note: `gw` shadows Vim's native format operator (rarely needed; use gq)
vim.keymap.set({ "n", "x", "o" }, "gw", function()
	hop.hint_words()
end, { desc = "jump to word (labels)" })
vim.keymap.set({ "n", "x", "o" }, "gl", function()
	hop.hint_lines()
end, { desc = "jump to line (labels)" })
vim.keymap.set({ "n", "x", "o" }, "gs", function()
	hop.hint_char2()
end, { desc = "jump to 2-char match" })
